In [1]:
##Create a white box neural network

import tensorflow as tf
from tensorflow.keras import layers, models

# Define a simple feedforward neural network
def create_white_box_nn(input_shape):
    model = models.Sequential()

    # Input layer
    model.add(layers.InputLayer(input_shape=input_shape))

    # Hidden layers
    model.add(layers.Dense(units=128, activation='relu'))
    model.add(layers.Dense(units=64, activation='relu'))

    # Output layer
    model.add(layers.Dense(units=1, activation='sigmoid'))

    return model

# Specify input shape (assuming a binary classification task with input features of size 10)
input_shape = (10,)

# Create the white-box neural network
white_box_nn = create_white_box_nn(input_shape)

# Display the model summary
white_box_nn.summary()




Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               1408      
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 9729 (38.00 KB)
Trainable params: 9729 (38.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [4]:
##Activation functions

##1. Sigmoid function
import math
import numpy as np

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

# Using numpy for vectorized operations
def sigmoid_np(x):
    return 1 / (1 + np.exp(-x))



In [5]:
##2. tanh function
import math
import numpy as np

def tanh(x):
    return (math.exp(2*x) - 1) / (math.exp(2*x) + 1)

# Using numpy for vectorized operations
def tanh_np(x):
    return np.tanh(x)


In [6]:
##3.RELU function
def relu(x):
    return max(0, x)

# Using numpy for vectorized operations
import numpy as np

def relu_np(x):
    return np.maximum(0, x)



In [7]:
##4.ELU function

import numpy as np

def elu(x, alpha=1.0):
    return np.where(x >= 0, x, alpha * (np.exp(x) - 1))

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = elu(x_values, alpha=1.0)
print(output_values)


[-0.86466472 -0.63212056  0.          1.          2.        ]


In [8]:
##5.PRELU function

import numpy as np

class PReLU:
    def __init__(self, alpha=0.01):
        self.alpha = alpha

    def __call__(self, x):
        return np.where(x >= 0, x, self.alpha * x)

# Example usage
prelu_activation = PReLU(alpha=0.01)
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = prelu_activation(x_values)
print(output_values)


[-0.02 -0.01  0.    1.    2.  ]


In [9]:
##6.Leaky RELU function

import numpy as np

def leaky_relu(x, alpha=0.01):
    return np.where(x >= 0, x, alpha * x)

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = leaky_relu(x_values, alpha=0.01)
print(output_values)


[-0.02 -0.01  0.    1.    2.  ]


In [10]:
##7.SELU function
import numpy as np

def selu(x, scale=1.0507, alpha=1.67326):
    return scale * np.where(x > 0, x, alpha * (np.exp(x) - 1))

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = selu(x_values)
print(output_values)


[-1.52016209 -1.11132754  0.          1.0507      2.1014    ]


In [11]:
##8.Softsign function

import numpy as np

def softsign(x):
    return x / (1 + np.abs(x))

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = softsign(x_values)
print(output_values)


[-0.66666667 -0.5         0.          0.5         0.66666667]


In [12]:
##9.Softplus

import numpy as np

def softplus(x):
    return np.log(1 + np.exp(x))

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = softplus(x_values)
print(output_values)


[0.12692801 0.31326169 0.69314718 1.31326169 2.12692801]


In [14]:
##10.Hard sigmoid

import numpy as np
def hard_sigmoid(x):
    return np.clip(0.16666667 * x + 0.5, 0, 1)
# Example usage
x_values = np.array([-3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0])
output_values = hard_sigmoid(x_values)
print(output_values)

[0.         0.16666666 0.33333333 0.5        0.66666667 0.83333334
 1.        ]


In [15]:
##11.Swish function

import numpy as np

def swish(x):
    return x * (1.0 / (1.0 + np.exp(-x)))

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = swish(x_values)
print(output_values)


[-0.23840584 -0.26894142  0.          0.73105858  1.76159416]


In [16]:
##12.Mish function

import numpy as np

def mish(x):
    return x * np.tanh(np.log(1 + np.exp(x)))

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = mish(x_values)
print(output_values)


[-0.25250148 -0.30340146  0.          0.86509839  1.94395896]


In [17]:
##Python code for chain rule

import sympy as sp

# Define symbols
x = sp.symbols('x')

# Define the inner and outer functions
g = x**2
f = sp.sin(g)

# Compute the derivatives
g_prime = sp.diff(g, x)
f_prime = sp.diff(f, x)

# Apply the chain rule
chain_rule_result = f_prime.subs(g, x**2) * g_prime

# Print the result
print("f'(x) =", f_prime)
print("g'(x) =", g_prime)
print("Chain Rule Result:", chain_rule_result)


f'(x) = 2*x*cos(x**2)
g'(x) = 2*x
Chain Rule Result: 4*x**2*cos(x**2)


In [18]:
##Function to perform back propagation

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def mean_squared_error(y_true, y_pred):
    return 0.5 * np.mean((y_true - y_pred) ** 2)

def mean_squared_error_derivative(y_true, y_pred):
    return y_pred - y_true

def initialize_weights(input_size, hidden_size, output_size):
    np.random.seed(42)
    weights_input_hidden = np.random.randn(input_size, hidden_size)
    weights_hidden_output = np.random.randn(hidden_size, output_size)
    return weights_input_hidden, weights_hidden_output

def forward_propagation(X, weights_input_hidden, weights_hidden_output):
    hidden_layer_input = np.dot(X, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output_layer_output = sigmoid(output_layer_input)
    return hidden_layer_output, output_layer_output

def backward_propagation(X, y, hidden_layer_output, output_layer_output, 
                         weights_input_hidden, weights_hidden_output, learning_rate):
    output_error = mean_squared_error_derivative(y, output_layer_output)
    output_delta = output_error * sigmoid_derivative(output_layer_output)

    hidden_error = output_delta.dot(weights_hidden_output.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)

    weights_hidden_output -= hidden_layer_output.T.dot(output_delta) * learning_rate
    weights_input_hidden -= X.T.dot(hidden_delta) * learning_rate

def train_neural_network(X, y, hidden_size, epochs, learning_rate):
    input_size = X.shape[1]
    output_size = 1

    weights_input_hidden, weights_hidden_output = initialize_weights(input_size, hidden_size, output_size)

    for epoch in range(epochs):
        hidden_layer_output, output_layer_output = forward_propagation(X, weights_input_hidden, weights_hidden_output)

        backward_propagation(X, y, hidden_layer_output, output_layer_output, 
                             weights_input_hidden, weights_hidden_output, learning_rate)

        if epoch % 1000 == 0:
            loss = mean_squared_error(y, output_layer_output)
            print(f"Epoch {epoch}, Loss: {loss}")

    return weights_input_hidden, weights_hidden_output

# Example usage
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

trained_weights_input_hidden, trained_weights_hidden_output = train_neural_network(X, y, hidden_size=4, epochs=10000, learning_rate=0.1)

# Test the trained network
_, predictions = forward_propagation(X, trained_weights_input_hidden, trained_weights_hidden_output)
print("Predictions:")
print(predictions)


Epoch 0, Loss: 0.14159479453221988
Epoch 1000, Loss: 0.1234468957069047
Epoch 2000, Loss: 0.11155406432451559
Epoch 3000, Loss: 0.07778517861398411
Epoch 4000, Loss: 0.03281496018045561
Epoch 5000, Loss: 0.014799615014231389
Epoch 6000, Loss: 0.008925515193170445
Epoch 7000, Loss: 0.00624985817255592
Epoch 8000, Loss: 0.004750368741015837
Epoch 9000, Loss: 0.0037992877772672815
Predictions:
[[0.09620443]
 [0.92303163]
 [0.92312117]
 [0.06383034]]


In [32]:
##Back propagation for ant colony optimization
import numpy as np

# Define the task (e.g., XOR)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Neural network architecture
input_size = 2
hidden_size = 4
output_size = 1

# ACO parameters
num_ants = 5
pheromone_matrix = np.ones((input_size * hidden_size + hidden_size * output_size,))

# Define the sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Define the neural network forward propagation
def forward_propagation(weights, X):
    input_hidden_weights = weights[:input_size * hidden_size].reshape(input_size, hidden_size)
    hidden_output_weights = weights[input_size * hidden_size:].reshape(hidden_size, output_size)

    hidden_layer_input = np.dot(X, input_hidden_weights)
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, hidden_output_weights)
    output_layer_output = sigmoid(output_layer_input)

    return output_layer_output

# Define the fitness function based on mean squared error
def fitness(weights):
    total_error = 0
    for xi, target in zip(X, y):
        output = forward_propagation(weights, xi)
        total_error += np.mean((output - target) ** 2)
    return -total_error  # Maximizing fitness, so negative of error

# ACO-inspired exploration
def explore_weights(pheromone_matrix):
    weights = np.random.rand(len(pheromone_matrix))
    weights = weights * pheromone_matrix
    return weights / np.sum(weights)

# Training loop
num_iterations = 100
learning_rate = 0.1

for iteration in range(num_iterations):
    for ant in range(num_ants):
        # Explore the weight space using ACO
        candidate_weights = explore_weights(pheromone_matrix)

        # Evaluate fitness
        fitness_candidate = fitness(candidate_weights)

        # Update pheromone based on fitness
        pheromone_matrix += learning_rate * (fitness_candidate - pheromone_matrix)

    # Print the best fitness in each iteration
    best_fitness = max(fitness(candidate_weights) for ant in range(num_ants))
    print(f"Iteration {iteration}, Best Fitness: {best_fitness}")

# Get the best weights from the pheromone matrix
best_weights = explore_weights(pheromone_matrix)

# Test the best weights
predictions = [forward_propagation(best_weights, xi) for xi in X]
print("\nFinal Predictions:")
print(predictions)


Iteration 0, Best Fitness: -1.0095604657361734
Iteration 1, Best Fitness: -1.0040480313601492
Iteration 2, Best Fitness: -1.0067162945978299
Iteration 3, Best Fitness: -1.0030817806282994
Iteration 4, Best Fitness: -1.0082331569501404
Iteration 5, Best Fitness: -1.0127640345587219
Iteration 6, Best Fitness: -1.0152376468245525
Iteration 7, Best Fitness: -1.0105918717655973
Iteration 8, Best Fitness: -1.0070662742387426
Iteration 9, Best Fitness: -1.0060008415633572
Iteration 10, Best Fitness: -1.0076667425073977
Iteration 11, Best Fitness: -1.0033938983630253
Iteration 12, Best Fitness: -1.0024119274294954
Iteration 13, Best Fitness: -1.003753841111412
Iteration 14, Best Fitness: -1.006883584977868
Iteration 15, Best Fitness: -1.0058747330445694
Iteration 16, Best Fitness: -1.005778087792939
Iteration 17, Best Fitness: -1.009414189492408
Iteration 18, Best Fitness: -1.0075631799859663
Iteration 19, Best Fitness: -1.0065880545620407
Iteration 20, Best Fitness: -1.0026394995475252
Iterat

In [31]:
##Back propagation for genetic algorithm

import numpy as np

# Define the task (e.g., XOR)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Define neural network architecture
input_size = 2
hidden_size = 4
output_size = 1

# Define genetic algorithm parameters
population_size = 10
mutation_rate = 0.1
num_generations = 100

# Initialize the population with random weights
population = [np.random.randn((input_size + 1) * hidden_size + (hidden_size + 1) * output_size) for _ in range(population_size)]

# Define the sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Define the neural network forward propagation
def forward_propagation(weights, X):
    # Extract weights for input to hidden layer and hidden to output layer
    input_hidden_weights = weights[:input_size * hidden_size].reshape(input_size, hidden_size)
    hidden_output_weights = weights[input_size * hidden_size:].reshape(hidden_size, output_size)

    # Input to hidden layer
    hidden_layer_input = np.dot(X, input_hidden_weights)
    hidden_layer_output = sigmoid(hidden_layer_input)

    # Hidden to output layer
    output_layer_input = np.dot(hidden_layer_output, hidden_output_weights)
    output_layer_output = sigmoid(output_layer_input)

    return output_layer_output

# Define the fitness function based on mean squared error
def fitness(weights):
    total_error = 0
    for xi, target in zip(X, y):
        output = forward_propagation(weights, xi)
        total_error += np.mean((output - target) ** 2)
    return -total_error  # Maximizing fitness, so negative of error

# Genetic algorithm loop
for generation in range(num_generations):
    # Evaluate fitness for each individual in the population
    fitness_scores = [fitness(individual) for individual in population]

    # Select parents based on fitness scores (roulette wheel selection)
    parents_indices = np.random.choice(range(population_size), size=2, p=fitness_scores / np.sum(fitness_scores))

    # Crossover (single-point crossover)
    crossover_point = np.random.randint(len(population[0]))
    child1 = np.concatenate((population[parents_indices[0]][:crossover_point], population[parents_indices[1]][crossover_point:]))
    child2 = np.concatenate((population[parents_indices[1]][:crossover_point], population[parents_indices[0]][crossover_point:]))

    # Mutation
    child1[np.random.rand(len(child1)) < mutation_rate] += np.random.randn(sum(np.random.rand(len(child1)) < mutation_rate))
    child2[np.random.rand(len(child2)) < mutation_rate] += np.random.randn(sum(np.random.rand(len(child2)) < mutation_rate))

    # Replace the least fit individuals with the new children
    least_fit_index = np.argmin(fitness_scores)
    population[least_fit_index] = child1
    population[(least_fit_index + 1) % population_size] = child2

    # Print the best fitness in each generation
    best_fitness = max(fitness_scores)
    print(f"Generation {generation}, Best Fitness: {best_fitness}")

# Get the best individual (weights) from the final population
best_weights = population[np.argmax(fitness_scores)]

# Test the best individual
predictions = [forward_propagation(best_weights, xi) for xi in X]
print("\nFinal Predictions:")
print(predictions)


ValueError: cannot reshape array of size 9 into shape (4,1)

In [30]:
##Back propagation for cultural algorithm

import numpy as np

# Define the task (e.g., XOR)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Define the neural network architecture
input_size = 2
hidden_size = 4
output_size = 1

# Initialize weights
weights_input_hidden = np.random.randn(input_size, hidden_size)
weights_hidden_output = np.random.randn(hidden_size, output_size)

# Define the sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training parameters
learning_rate = 0.1
epochs = 10000

# Training loop
for epoch in range(epochs):
    # Forward propagation
    hidden_layer_input = np.dot(X, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output_layer_output = sigmoid(output_layer_input)

    # Backpropagation
    output_error = y - output_layer_output
    output_delta = output_error * sigmoid_derivative(output_layer_output)

    hidden_error = output_delta.dot(weights_hidden_output.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)

    # Update weights
    weights_hidden_output += hidden_layer_output.T.dot(output_delta) * learning_rate
    weights_input_hidden += X.T.dot(hidden_delta) * learning_rate

    # Print the loss every 1000 epochs
    if epoch % 1000 == 0:
        loss = np.mean(np.square(output_error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Test the trained network
hidden_layer_output = sigmoid(np.dot(X, weights_input_hidden))
final_output = sigmoid(np.dot(hidden_layer_output, weights_hidden_output))
print("\nFinal Output:")
print(final_output)


Epoch 0, Loss: 0.24688305216322626
Epoch 1000, Loss: 0.1790691700409746
Epoch 2000, Loss: 0.11833999071584195
Epoch 3000, Loss: 0.0901214480083568
Epoch 4000, Loss: 0.07902366765388376
Epoch 5000, Loss: 0.07375055136729795
Epoch 6000, Loss: 0.07075850718698443
Epoch 7000, Loss: 0.0688048982746113
Epoch 8000, Loss: 0.06732676417849096
Epoch 9000, Loss: 0.06587313344193534

Final Output:
[[0.0608975 ]
 [0.92675102]
 [0.92694637]
 [0.48642503]]
